package views

import (
	"strconv"
	"strings"
)

// taskColourBars is the per-task colour palette used by the timesheet
// to mark sessions that belong to the same task with a matching 2px
// top-border. 12 hues × 3 shades (light 400/600/800, dark 300/500/700)
// = 36 entries. Hues avoid:
//   - red (delete/error)
//   - amber/orange (active-session indicator)
//   - blue (today/selected)
//   - neutral zinc (default chip background)
//
// Each entry is a Tailwind border-top colour pair: light-mode shade
// for readable contrast on a zinc-100 chip, dark-mode shade lifted
// one step for the inverted background.
//
// Listed verbatim (not generated by loop) so Tailwind's class scanner
// can pick every utility name out of source. Order is irrelevant -
// taskColourBar() hashes into the slice deterministically.
var taskColourBars = []string{
	"border-t-indigo-400 dark:border-t-indigo-300",
	"border-t-indigo-600 dark:border-t-indigo-500",
	"border-t-indigo-800 dark:border-t-indigo-700",
	"border-t-violet-400 dark:border-t-violet-300",
	"border-t-violet-600 dark:border-t-violet-500",
	"border-t-violet-800 dark:border-t-violet-700",
	"border-t-purple-400 dark:border-t-purple-300",
	"border-t-purple-600 dark:border-t-purple-500",
	"border-t-purple-800 dark:border-t-purple-700",
	"border-t-fuchsia-400 dark:border-t-fuchsia-300",
	"border-t-fuchsia-600 dark:border-t-fuchsia-500",
	"border-t-fuchsia-800 dark:border-t-fuchsia-700",
	"border-t-pink-400 dark:border-t-pink-300",
	"border-t-pink-600 dark:border-t-pink-500",
	"border-t-pink-800 dark:border-t-pink-700",
	"border-t-rose-400 dark:border-t-rose-300",
	"border-t-rose-600 dark:border-t-rose-500",
	"border-t-rose-800 dark:border-t-rose-700",
	"border-t-emerald-400 dark:border-t-emerald-300",
	"border-t-emerald-600 dark:border-t-emerald-500",
	"border-t-emerald-800 dark:border-t-emerald-700",
	"border-t-teal-400 dark:border-t-teal-300",
	"border-t-teal-600 dark:border-t-teal-500",
	"border-t-teal-800 dark:border-t-teal-700",
	"border-t-cyan-400 dark:border-t-cyan-300",
	"border-t-cyan-600 dark:border-t-cyan-500",
	"border-t-cyan-800 dark:border-t-cyan-700",
	"border-t-sky-400 dark:border-t-sky-300",
	"border-t-sky-600 dark:border-t-sky-500",
	"border-t-sky-800 dark:border-t-sky-700",
	"border-t-lime-400 dark:border-t-lime-300",
	"border-t-lime-600 dark:border-t-lime-500",
	"border-t-lime-800 dark:border-t-lime-700",
	"border-t-yellow-400 dark:border-t-yellow-300",
	"border-t-yellow-600 dark:border-t-yellow-500",
	"border-t-yellow-800 dark:border-t-yellow-700",
}

// taskColourBar maps a TaskUUID to a deterministic top-border palette
// entry. The same UUID always returns the same colour so a task's
// sessions read as a connected ribbon across the week. Empty or
// malformed UUIDs fall back to a neutral zinc bar so the chip layout
// stays consistent with the bar always present.
//
// UUIDs are already cryptographic-quality random strings - parsing
// the first 8 hex chars as uint32 distributes them across the
// palette uniformly. Cheaper than running a hash function and good
// enough given the input has no adversarial property.
func taskColourBar(uuid string) string {
	hex := strings.ReplaceAll(uuid, "-", "")
	if len(hex) < 8 {
		return "border-t-zinc-300 dark:border-t-zinc-600"
	}
	n, err := strconv.ParseUint(hex[:8], 16, 32)
	if err != nil {
		return "border-t-zinc-300 dark:border-t-zinc-600"
	}
	return taskColourBars[n%uint64(len(taskColourBars))]
}

// urgencyTier collapses Taskwarrior's open-ended urgency score into the four
// ordinal levels used by tierSolid/tierLight/tierBadge: low/med/high/critical.
// Thresholds chosen to spread the band across typical Taskwarrior data without
// either flooding "critical" or starving the high tiers.
func urgencyTier(score float64) string {
	switch {
	case score >= 9:
		return "critical"
	case score >= 6:
		return "high"
	case score >= 3:
		return "med"
	default:
		return "low"
	}
}

// tierSolid: filled chip with high-contrast text. For due-day chips and the
// urgency bar. Yellow uses dark text because yellow-on-white can't meet AA.
//
// Dark mode: blue/orange/red read well as-is on a dark page. Yellow-400 on
// a dark page can wash out, so we bump to yellow-500 with the same dark
// text - keeps the "med = yellow" identity but with more saturation.
//
// One row in the four-tier palette. The siblings (tierLight, tierBadge,
// urgencyBarColour) all consume the same urgencyTier() input so a score
// hitting "high" reads as orange in every surface. Keep the four functions'
// hue identity in sync if you tweak any one of them.
func tierSolid(tier string) string {
	switch tier {
	case "critical":
		return "bg-red-600 text-white"
	case "high":
		return "bg-orange-700 text-white"
	case "med":
		return "bg-yellow-400 text-zinc-900 dark:bg-yellow-500"
	default:
		return "bg-blue-600 text-white"
	}
}

// tierLight: light fill, dark text, inset ring. For scheduled-day chips
// (multi-day spans before the due day).
//
// Dark mode inverts the chip - very dark coloured fill + light coloured text
// + a still-visible ring - so the "scheduled day" remains distinguishable
// from the "due day" (solid) at a glance, the same colourblind-safe contrast
// distinction we rely on in light mode.
func tierLight(tier string) string {
	switch tier {
	case "critical":
		return "bg-red-100 text-red-900 ring-1 ring-inset ring-red-300 dark:bg-red-950/60 dark:text-red-200 dark:ring-red-800"
	case "high":
		return "bg-orange-100 text-orange-900 ring-1 ring-inset ring-orange-400 dark:bg-orange-950/60 dark:text-orange-200 dark:ring-orange-800"
	case "med":
		return "bg-yellow-100 text-yellow-900 ring-1 ring-inset ring-yellow-400 dark:bg-yellow-950/60 dark:text-yellow-200 dark:ring-yellow-800"
	default:
		return "bg-blue-100 text-blue-900 ring-1 ring-inset ring-blue-300 dark:bg-blue-950/60 dark:text-blue-200 dark:ring-blue-800"
	}
}

// tierBadge: light fill + dark text, no ring. For the small inline due-date
// badge inside row.templ - kept minimal so it doesn't compete with the row.
func tierBadge(tier string) string {
	switch tier {
	case "critical":
		return "bg-red-100 text-red-900 dark:bg-red-950/60 dark:text-red-200"
	case "high":
		return "bg-orange-100 text-orange-900 dark:bg-orange-950/60 dark:text-orange-200"
	case "med":
		return "bg-yellow-100 text-yellow-900 dark:bg-yellow-950/60 dark:text-yellow-200"
	default:
		return "bg-blue-100 text-blue-900 dark:bg-blue-950/60 dark:text-blue-200"
	}
}

// urgencyPercent maps Taskwarrior's open-ended urgency score to 0-100. Anything
// above ~10 is exceptional and clamps at 100.
func urgencyPercent(score float64) float64 {
	if score <= 0 {
		return 0
	}
	pct := score * 10
	if pct > 100 {
		pct = 100
	}
	return pct
}

// urgencyBarColour: the thin horizontal urgency-meter bar at the right of each
// row. Uses the 4-tier palette but strips text colour (the bar has no text);
// solid background only. Yellow gets the same dark-mode bump as tierSolid so
// the bar reads cleanly against bg-zinc-700 (the bar's track in dark mode).
//
// Sibling of dueBadgeClass (format.go): both are score/time-derived class
// helpers that bottom out on the same urgencyTier()-driven palette, so a
// "critical" row badge and a "critical" urgency bar always share a hue.
// urgencyDotColour returns the background-only Tailwind class for the
// small dot indicators used in the mobile calendar strip.
func urgencyDotColour(score float64) string {
	switch urgencyTier(score) {
	case "critical":
		return "bg-red-500"
	case "high":
		return "bg-orange-400"
	case "med":
		return "bg-yellow-400"
	default:
		return "bg-blue-500"
	}
}

func urgencyBarColour(score float64) string {
	switch urgencyTier(score) {
	case "critical":
		return "bg-red-600"
	case "high":
		return "bg-orange-700"
	case "med":
		return "bg-yellow-400 dark:bg-yellow-500"
	default:
		return "bg-blue-600"
	}
}
